
version: '3.6'

services:
    task-network-env:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - PROJECT_DIR=${PROJECT_DIR}
        image: task-network-env:latest
        volumes:
            - ./:${PROJECT_DIR}
        shm_size: 7gb
